name: IceHost Hy2 Final
on:
  schedule:
    - cron: '15 */5 * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Hysteria2 Proxy
        run: |
          # 下载官方 Hy2 二进制
          wget https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64 -O hy2
          chmod +x hy2
          
          # 写入你的节点配置
          cat <<EOF > hy2_config.yaml
          server: 83.168.94.238:30045
          auth: 9afd1229-b893-40c1-84dd-51e7ce204913
          tls:
            sni: www.bing.com
            insecure: true
          socks5:
            listen: 127.0.0.1:1080
          transport:
            type: udp
          EOF
          
          # 后台运行并隐藏输出
          ./hy2 client -c hy2_config.yaml > /dev/null 2>&1 &
          sleep 12 # 留出时间进行握手

      - name: Install Browser
        run: |
          pip install playwright requests
          playwright install chromium
          
      - name: Run Script
        env:
          ICE_EMAIL: ${{ secrets.ICE_EMAIL }}
          ICE_PASSWORD: ${{ secrets.ICE_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
